# Generated by Django 2.0.7 on 2018-07-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0002_auto_20180730_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='creditosA',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='creditosT',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='dataFim',
            field=models.DateField(default='2018-07-30'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='dataIni',
            field=models.DateField(default='2018-07-30'),
        ),
    ]
