# Generated by Django 2.0.7 on 2018-07-31 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0005_auto_20180730_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='dataFim',
            field=models.DateField(blank=True, default='2018-07-31'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='dataIni',
            field=models.DateField(blank=True, default='2018-07-31'),
        ),
    ]
