# Generated by Django 2.1 on 2018-08-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0006_auto_20180731_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='dataFim',
            field=models.DateField(blank=True, default='2018-08-06'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='dataIni',
            field=models.DateField(blank=True, default='2018-08-06'),
        ),
    ]
