# Generated by Django 2.1 on 2018-08-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0007_auto_20180806_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='dataFim',
            field=models.DateField(blank=True, default='2018-08-12'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='dataIni',
            field=models.DateField(blank=True, default='2018-08-12'),
        ),
    ]
