# Generated by Django 2.1 on 2018-08-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0008_auto_20180812_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='dataFim',
            field=models.DateField(blank=True, default='2018-08-29'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='dataIni',
            field=models.DateField(blank=True, default='2018-08-29'),
        ),
    ]
