# Generated by Django 2.1 on 2018-08-22 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disciplinas', '0009_auto_20180822_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('explicacao', models.CharField(blank=True, max_length=3000)),
                ('criado_em', models.DateTimeField(editable=False)),
                ('editado_em', models.DateTimeField()),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criador', to=settings.AUTH_USER_MODEL)),
                ('disc_pai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplinas.Disciplina')),
                ('editado_por', models.ManyToManyField(blank=True, related_name='editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
