# Generated by Django 2.1 on 2018-08-22 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0010_topico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('upload', models.FileField(upload_to='uploads/')),
                ('formato', models.CharField(max_length=10)),
                ('tamanhoKB', models.DecimalField(decimal_places=1, max_digits=12)),
            ],
        ),
        migrations.AlterField(
            model_name='topico',
            name='editado_em',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='topico_pai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplinas.Topico'),
        ),
    ]
