# Generated by Django 2.1 on 2018-09-14 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0012_auto_20180911_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='titulo',
        ),
    ]
