# Generated by Django 2.1 on 2018-09-14 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0012_auto_20180911_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='criado_em',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 14, 9, 41, 29, 519499), editable=False),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='editado_em',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 14, 9, 41, 29, 519499), editable=False),
        ),
    ]
