# Generated by Django 2.1 on 2018-09-15 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0013_auto_20180914_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='criado_em',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 15, 9, 59, 26, 104349), editable=False),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='editado_em',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 15, 9, 59, 26, 104349)),
        ),
    ]
