# Generated by Django 2.1.1 on 2018-09-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0014_resposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='upload',
            field=models.FileField(upload_to=''),
        ),
    ]
