# Generated by Django 2.1 on 2018-09-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0015_auto_20180915_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='editado_em',
            field=models.DateTimeField(default='2018-08-01', editable=False),
        ),
    ]
