# Generated by Django 2.1.1 on 2018-09-16 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0015_auto_20180916_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arquivo',
            old_name='nome',
            new_name='name',
        ),
    ]
