# Generated by Django 2.1 on 2018-09-16 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0014_resposta'),
        ('disciplinas', '0016_auto_20180915_1149'),
    ]

    operations = [
    ]
