# Generated by Django 2.1.1 on 2018-09-16 21:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0016_auto_20180916_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivo',
            name='formato',
        ),
        migrations.RemoveField(
            model_name='arquivo',
            name='tamanho',
        ),
        migrations.AddField(
            model_name='arquivo',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
