# Generated by Django 2.1.1 on 2018-09-16 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0017_auto_20180916_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
