# Generated by Django 2.1.1 on 2018-09-22 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0017_merge_20180916_1347'),
        ('disciplinas', '0018_arquivo_size'),
    ]

    operations = [
    ]
