# Generated by Django 2.1.1 on 2018-09-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0019_merge_20180922_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=12),
        ),
    ]
