# Generated by Django 2.1 on 2018-08-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0008_auto_20180812_2134'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='disciplinas',
            field=models.ManyToManyField(blank=True, related_name='disciplinas_usuario', to='disciplinas.Disciplina'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nusp',
            field=models.IntegerField(default=0),
        ),
    ]
